comments = {
    1: {"comment_id": 1, "post_id": 1, "user_id": 5, "content": "좋은 글 감사합니다!"},
    2: {"comment_id": 2, "post_id": 1, "user_id": 12, "content": "완전 공감해요"},
    3: {"comment_id": 3, "post_id": 2, "user_id": 7, "content": "재밌게 읽고 갑니다"},
    4: {"comment_id": 4, "post_id": 3, "user_id": 8, "content": "이건 처음 알았네요"},
    5: {"comment_id": 5, "post_id": 3, "user_id": 4, "content": "좋은 정보예요"},
    6: {"comment_id": 6, "post_id": 3, "user_id": 17, "content": "감사합니다!"},
    7: {"comment_id": 7, "post_id": 5, "user_id": 1, "content": "도움 됐어요"},
    8: {"comment_id": 8, "post_id": 7, "user_id": 3, "content": "이거 참고해야겠네요"},
    9: {"comment_id": 9, "post_id": 8, "user_id": 9, "content": "정말 유익합니다"},
    10: {"comment_id": 10, "post_id": 8, "user_id": 11, "content": "잘 보고 가요"},
    11: {"comment_id": 11, "post_id": 9, "user_id": 19, "content": "대박 아이디어네요"},
    12: {"comment_id": 12, "post_id": 12, "user_id": 6, "content": "정리 깔끔하네요"},
    13: {"comment_id": 13, "post_id": 13, "user_id": 2, "content": "이거 맞나요? 궁금해요"},
    14: {"comment_id": 14, "post_id": 13, "user_id": 10, "content": "잘 설명해주셨네요"},
    15: {"comment_id": 15, "post_id": 14, "user_id": 16, "content": "좋아요 누르고 갑니다"},
    16: {"comment_id": 16, "post_id": 15, "user_id": 8, "content": "오오 유용해요"},
    17: {"comment_id": 17, "post_id": 17, "user_id": 5, "content": "한번 따라해볼게요"},
    18: {"comment_id": 18, "post_id": 17, "user_id": 18, "content": "좋은 하루 되세요~"},
    19: {"comment_id": 19, "post_id": 20, "user_id": 7, "content": "완벽한 설명 감사해요"},
    20: {"comment_id": 20, "post_id": 22, "user_id": 14, "content": "이 글 도움 됐어요!"},
    21: {"comment_id": 21, "post_id": 23, "user_id": 13, "content": "북마크 했습니다"},
    22: {"comment_id": 22, "post_id": 23, "user_id": 1, "content": "이건 몰랐네요"},
    23: {"comment_id": 23, "post_id": 24, "user_id": 19, "content": "감사합니다"},
    24: {"comment_id": 24, "post_id": 26, "user_id": 4, "content": "좋아요👍"},
    25: {"comment_id": 25, "post_id": 27, "user_id": 6, "content": "이거 유용하네요"},
    26: {"comment_id": 26, "post_id": 27, "user_id": 12, "content": "또 올려주세요"},
    27: {"comment_id": 27, "post_id": 28, "user_id": 8, "content": "완전 공감.."},
    28: {"comment_id": 28, "post_id": 28, "user_id": 3, "content": "좋은 정보네요"},
    29: {"comment_id": 29, "post_id": 29, "user_id": 11, "content": "감사해요"},
    30: {"comment_id": 30, "post_id": 29, "user_id": 20, "content": "고맙습니다"},
    31: {"comment_id": 31, "post_id": 30, "user_id": 15, "content": "좋아요 누름"},
    32: {"comment_id": 32, "post_id": 31, "user_id": 11, "content": "도움됐어요!"},
    33: {"comment_id": 33, "post_id": 32, "user_id": 9, "content": "굿굿"},
    34: {"comment_id": 34, "post_id": 33, "user_id": 2, "content": "정독했습니다"},
    35: {"comment_id": 35, "post_id": 34, "user_id": 10, "content": "덕분에 이해했어요"},
    36: {"comment_id": 36, "post_id": 35, "user_id": 17, "content": "진짜 유용"},
    37: {"comment_id": 37, "post_id": 36, "user_id": 5, "content": "감사합니다😊"},
    38: {"comment_id": 38, "post_id": 37, "user_id": 13, "content": "대단합니다"},
    39: {"comment_id": 39, "post_id": 37, "user_id": 16, "content": "멋져요!"},
    40: {"comment_id": 40, "post_id": 38, "user_id": 7, "content": "좋은 팁 감사합니다"},
    41: {"comment_id": 41, "post_id": 40, "user_id": 14, "content": "완전 유용하네요"},
    42: {"comment_id": 42, "post_id": 41, "user_id": 20, "content": "올려주셔서 감사해요"},
    43: {"comment_id": 43, "post_id": 42, "user_id": 18, "content": "또 올려주세요!"},
    44: {"comment_id": 44, "post_id": 43, "user_id": 4, "content": "잘 보고 가요~"},
    45: {"comment_id": 45, "post_id": 44, "user_id": 6, "content": "이 글 최고"},
    46: {"comment_id": 46, "post_id": 45, "user_id": 19, "content": "이런 글 많이 주세요"},
    47: {"comment_id": 47, "post_id": 46, "user_id": 3, "content": "크으..."}, 
    48: {"comment_id": 48, "post_id": 47, "user_id": 11, "content": "고맙습니당"},
    49: {"comment_id": 49, "post_id": 48, "user_id": 1, "content": "와 잘하신다"},
    50: {"comment_id": 50, "post_id": 49, "user_id": 2, "content": "유익했어요!"},
}

next_comment_id = 51
